issue#254_add_PGID-UID_to_Rockon_doc
rockstor/rockstor-doc pull request #255
Opened 2020-12-19 00:41 UTC by Hooverdan96

Fixes #254 

### This pull request's proposal
Adding small subsection mentioning UID and GID usage and where to find them during Rock-on configuration.

### Checklist
- [X] With the proposed changes no Sphinx errors or warnings are generated.
- [ ] I have added my name to the AUTHORS file, if required (descending alphabetical order).

Log output:
Running Sphinx v3.3.1
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 1 source files that are out of date
updating environment: 0 added, 1 changed, 0 removed
reading sources... [100%] docker-based-rock-ons/overview                                                                                                                                                                     
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] index                                                                                                                                                                                               
generating indices... genindex done
writing additional pages... search done
copying images... [100%] docker-based-rock-ons/addlabels_labels_selection.png                                                                                                                                                
copying static files... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded.

2020-12-25 14:21 UTC, FroggyFlox requested changes
@Hooverdan96 , nicely done!

Thanks a lot for improving our documentation on this, this was indeed an important point to detail so it's really helpful to have it in our documentation!

I only have a few minor style edits, mostly related to style recommendations for RST files:
- max character lengths: 79
- no trailing space at the end of line

I'm looking into finding a way to automate this but for the moment we need to do this manually, unfortunately.
Once these edits are in, I'll test them once more before merging your work.

Thanks again!

2020-12-25 14:21 UTC, FroggyFlox commented on docker-based-rock-ons/overview.rst
> +.. _user_group:
I would prefer further specification to differentiate it from our Users/Groups dedicated page:
```suggestion
.. _rockons_user_group:
```

2020-12-25 14:21 UTC, FroggyFlox commented on docker-based-rock-ons/overview.rst
> +During the configuration of Rock-ons, quite a few require the specification of a User ID (UID) and/or a User Group ID (GID). Aside from the various options using the command line to determine existin
Minor style edits (rst style recommends line length of 79 characters max):
```suggestion
During the configuration of Rock-ons, quite a few require the specification of a
User ID (UID) and/or a Group ID (GID). Aside from the various options using the
command line to determine existing UIDs and GIDs, the simplest way is to take
advantage of the User and/or Group management screens. Navigate to System
--> Users (or Groups if necessary).
```

2020-12-25 14:21 UTC, FroggyFlox commented on docker-based-rock-ons/overview.rst
> +The two highlighted columns show the UID and GID. For example, the user plex had the UID 1001, as well as the GID 1001, which could then be used to set up the Plex Rock-on.
Minor style edits:
```suggestion
The two highlighted columns show the UID and GID. In the example above, the
user :code:`plex` has the UID 1001, as well as the GID 1001, which could then
be used to set up the Plex rock-on.
```

2020-12-25 21:19 UTC, Hooverdan96 commented
@FroggyFlox - thanks for the review. All of the above suggestions are sensible, and I have committed them. I obviously didn't read the style guide, so thanks for pointing out the 79 character max limit. I was looking for a UI based Sphinx editor but had only found an online one at this time. I will remember for next time.

2020-12-27 15:59 UTC, FroggyFlox approved these changes

2020-12-27 16:01 UTC, FroggyFlox commented
Thanks for the edits, @Hooverdan96!

Everything looks well in my most recent test so I'm going to merge and publish it now. Thanks again for your continued efforts and contributions!

2020-12-27 16:01 UTC, merged