Reorganize Table Of Content (#284)
rockstor/rockstor-doc pull request #290
Opened 2021-07-25 16:06 UTC by FroggyFlox

Fixes #284.
@phillxnet, ready for review.

### This pull request's proposal
As discussed in #284, this pull-request (PR) reorganizes the docs in an effort to cut down on the number of top level headings and thus simplify how the information is presented to the user. The overall aim was of course to drastically improve clarity and ease to find information of interest.

The second biggest change in this PR is the addition of the sphinx extension [rediraffe](https://github.com/wpilibsuite/sphinxext-rediraffe) to automatically track and generate html redirects for all pages that were removed/renamed/deleted. All these redirects can be found in the `redirects.txt` file. @phillxnet, note that we will need to integrate rediraffe into our back-end so that the extension writes the redirects when running `make html`.

Another extension change is the deprecation of `sphinxcontrib-fulltoc` as this was not required anymore. The `layout.html` was adapted accordingly so that we can still show the full toc and not just the local toc.

@phillxnet, my apologies for not being able to break all these changes into multiple commits... I realize it makes it difficult to review.

### Summary of changes
- Deprecate the sphinxcontrib-fulltoc extension
- Add sphinxext-rediraffe extension (#284)
- Reorganize TOC to follow Web-UI structure
- Follow Docutils guideline for max line length of 79 char
- Write redirects with rediraffewritediff
- Remove unused Indices and Tables section in index.rst
- Delete ununsed image files

### Checklist
- [ ] With the proposed changes no Sphinx errors or warnings are generated.
- [ ] I have added my name to the AUTHORS file, if required (descending alphabetical order).

2021-07-26 12:19 UTC, FroggyFlox commented
@phillxnet, sorry for the additional commits there; I should have tested that branch in a PR against my own fork to troubleshoot and fix our Github workflow there. Everything is now OK on this front and I'm glad I did update that as it highlighted an incorrect redirect for `update_channels.rst` (backslash instead of forward slash)--I'm liking the `rediraffecheckdiff` now :-) .

Everything should now be OK, though.

2021-07-26 17:30 UTC, phillxnet commented
@FroggyFlox Just now having a look at this rather magnificent re-work re overall arrangement & build enhancement of our entire docs. Nice.

Looking good so far. Just noting some warnings re our backend patching system used to test this pr:
```
./290.patch:80565: trailing whitespace.
                    {%- endif %}                
./290.patch:80586: trailing whitespace.
  
./290.patch:80627: trailing whitespace.
  
./290.patch:80633: trailing whitespace.
  
./290.patch:80635: trailing whitespace.
  
warning: squelched 176 whitespace errors
warning: 181 lines add whitespace errors.
```
from the patch file presented by GitHub for this pr, retrieved via:
```
curl -L https://github.com/rockstor/rockstor-doc/pull/290.patch -o 290.patch
```
Don't make any changes on this pr based on this report as it's not worth it. We can always address these, if they are 'real', in thier own far less imoprtant issue.

I'll stagger on for now with our backend changes re:

> @phillxnet, note that we will need to integrate rediraffe into our back-end so that the extension writes the redirects when running `make html`.

Nearly there.

2021-07-26 18:34 UTC, phillxnet commented
Getting one of our exiting important Web-UI embedded links from our local test webserver post pr merge:
```
wget http://build.lan/docs/update-channels/update_channels.html
...
HTTP request sent, awaiting response... 200 OK
Length: 521 [text/html]
Saving to: ‘update_channels.html’

update_channels.html                      100%[=====================================================================================>]     521  --.-KB/s    in 0s      

2021-07-26 19:00:09 (57.3 MB/s) - ‘update_channels.html’ saved [521/521]
```
Which is a browser based (read client side) redirect:

```
<html>
    <head>
        <noscript>
            <meta http-equiv="refresh" content="0; url=../interface/system/update_channels.html"/>
        </noscript>
    </head>
    <body>
        <script>
            window.location.href = '../interface/system/update_channels.html' + (window.location.search || '') + (window.location.hash || '');
        </script>
        <p>You should have been redirected.</p>
        <a href="../interface/system/update_channels.html">If not, click here to continue.</a>
    </body>
</html>

```

And when pasting the same link into a browser we are redirected to:

`
http://build.lan/docs/interface/system/update_channels.html
`

and we have server logs to reflect this successful forward:
```
 - - [26/Jul/2021:19:18:13 +0100] "GET /docs/update-channels/update_channels.html HTTP/1.1" 200 521 "-" ...
 - - [26/Jul/2021:19:18:14 +0100] "GET /docs/interface/system/update_channels.html HTTP/1.1" 200 19371 "http://build.lan/docs/update-channels/update_channels.html" ...
```

I see more now how rediraffe is doing this.

2021-07-26 19:18 UTC, phillxnet requested changes
@FroggyFlox Well that was an eye full. This is all fantastic stuff and our docs are in a much better state/format post these changes. I've only noticed only a single regression regarding our favouring internal references rather than external url's when linking to other part of the docs. I've marked it as a request change as I'm guessign this was an unintentional missed merge / rebase of sorts given the extensive amount of work involved in this pull request.

Let me know if you think we should skip this trivial regression and I'll merge as is and we can pick that up later.

Thanks for a massive amount of effort on this far reaching pull request and my apologies for not catching everything. It's rather impractical to review every change with so many file moves so I think we are best going with what little I've found and merging so we can take it in much smaller steps from there on :) .

2021-07-26 19:18 UTC, phillxnet commented on installation/quickstart.rst
> -
Well that was a surprise. I was sure we had removed all of these links. Nice find / fix.

2021-07-26 19:18 UTC, phillxnet commented on interface/docker-based-rock-ons/netdata_official.rst
> +.. image:: /images/interface/docker-based-rock-ons/netdata_docker_group.png
Thanks for standardising how we reference the "/images" directory. I'd not noticed the disparate use.

2021-07-26 23:29 UTC, FroggyFlox commented on howtos/home_nas_guide.rst
> +<https://rockstor.com/docs/quickstart.html#minimum-system-requirements>`_
You are entirely correct... this must be the result of an incorrect rebase. I'll commit the changes manually to get these things in order.

2021-07-26 23:46 UTC, FroggyFlox commented on howtos/home_nas_guide.rst
> +<https://rockstor.com/docs/quickstart.html#minimum-system-requirements>`_
@phillxnet, fixed as of https://github.com/rockstor/rockstor-doc/pull/290/commits/5b48a2bc78884dc1d3797154bcc44d0bc5bcedd2

2021-07-26 23:55 UTC, FroggyFlox commented
Thanks a lot for your review and catching that regression... I'm not sure how but it does look like a screw-up while rebasing, indeed... Whatever happened for the internal link, I switched it back to what it should be so it should be good this time.

Thanks again!

2021-07-27 12:35 UTC, phillxnet approved these changes

2021-07-27 12:45 UTC, phillxnet commented
@FroggyFlox This is quite the improvement. Thanks for all your efforts on this one. I'm bound to have missed some issues in it's review and apologies for that in advance but it's clearly, for me, a welcome step-up in our docs overall. They seemed to have gotten into quite the disarray unfortunately. They now look far less intimidating and 'wall-of-text' like, and more like a hand-book which is perfect.

Chuffed to merge and will then experimentally publish and test the live https variant. Should all be good thought from my local http tests.

For those concerned about our adoption here of client side redirects, it is appreciated that this is sub-optimal; however in the light of maintaining so many, potentially unending, redirects over time the value of preserving links baked into our older Web-UI instances, and forum numerous  threads, out weights the relatively cheap 'cost' of a repo (git) maintained redirection system.

I would like to join @FroggyFlox in his praise / appreciation of the fine work done by the [rediraffe](https://github.com/wpilibsuite/sphinxext-rediraffe) team who helped us make this major reorganisation of our docs possible.

2021-07-27 12:45 UTC, merged

2021-07-27 14:56 UTC, phillxnet commented
@FroggyFlox The result of this pull request's merge is now published to production. Looks nice there.