On branch issue#451_refactor_Rock-on_contribution
rockstor/rockstor-doc pull request #452
Opened 2023-09-21 21:17 UTC by Hooverdan96

Fixes #451.

### This pull request's proposal
 Changes to be committed:
	modified:   contribute/contribute_rockons.rst
	modified:   interface/overview.rst
- refactor, move and include contribution instructions from Rock-on repository into Rockstor documentation.
- Minor spelling/formulation corrections in both files

### Checklist
- [X] With the proposed changes no Sphinx errors or warnings are generated.
- [X] I have added my name to the AUTHORS file, if required (descending alphabetical order).

2023-09-21 22:01 UTC, Hooverdan96 commented
There are now 3 `403` errors left during linkcheck - these seem to be new, the website links work if I visit them manually. Suspect it might be a block due to "source" being github for hitting that link, or it's somewhat related to one of the issues I found while researching where the Sphinx/linkcheck  is having some issues for re-authorizing, due to the underlying python version and whatnot ...

2023-09-22 12:32 UTC, phillxnet commented
@Hooverdan96 Thanks for seeing to this modification/normalisation re our contribution docs. Much appreciated.
Re:
> There are now 3 403 errors
Same here when run locally: I think we just find alternatives to these as all three have pop-up adverts in anyway. So likely we can find a more canonical source for these 2 nfs and 1 sssd-ad man pages.

2023-09-22 12:54 UTC, FroggyFlox commented
Thanks a lot indeed, @Hooverdan96 !

With regards to finding a better link to manpages, may I suggest manpages.opensuse.org? Better suited to us and ad-free.

2023-09-22 13:09 UTC, phillxnet requested changes
@Hooverdan96 This is a great improvement. I was going to merge as-is but the html tags were the tipping point :). See what you think of the suggestions and I can pop this in directly there after hopefully.

Thanks for your ongoing work re improving our docs and code.

2023-09-22 13:09 UTC, phillxnet commented on contribute/contribute_rockons.rst
> +If you like to share your app with rest of the Rockstor community, open
```suggestion
If you would like to share your app with the rest of the Rockstor community, open
```
A little rewording suggestion if it takes your fancy :)

2023-09-22 13:09 UTC, phillxnet commented on contribute/contribute_rockons.rst
> +profile which serves as your private git remote called origin. The next few
```suggestion
profile which serves as your personal git remote called origin. The next few
```
I had thought a default fork in this context was non private, ergo 'personal' suggested word change.

2023-09-22 13:09 UTC, phillxnet commented on contribute/contribute_rockons.rst
> +with git and use an IDE like Eclipse, you can achieve the same outcome in a
```suggestion
with git and use an IDE, you can achieve the same outcome in a
```

Removing specific reference while I see it.

2023-09-22 14:38 UTC, Hooverdan96 commented
I guess I didn't check the text enough after copying it ... thanks for the additional eyes on it, and the rewording suggestions made sense as well.
I will create a separate issue/pull request to change the man-page targets, especially since those are in different parts of the documentation. @FroggyFlox thanks for the suggestion, the opensuse source makes even more sense to us now 💯

2023-09-22 14:41 UTC, Hooverdan96 commented
Once you're satisfied with the changes, I can squash them into one commit (though I know you mentioned that it's probably less relevant for the documentation).

2023-09-25 12:01 UTC, phillxnet approved these changes

2023-09-25 12:07 UTC, phillxnet commented
@Hooverdan96 Thanks again. About to merge. Re squashing I think it's less important to squash in docs/rock-ons/website as eases review / additional attribution / contributor burden: and clean history is less important than in code repositories. Plus we have only one branch in these repositories. So cherry picking requirement from one branch to another is not a thing.

2023-09-25 12:09 UTC, merged

2023-09-25 12:10 UTC, phillxnet commented
PR product PRODUCTION published.