Add linkcheck to Sphinx instructions
rockstor/rockstor-doc pull request #456
Opened 2023-09-22 16:47 UTC by Hooverdan96

Fixes #455. 

### This pull request's proposal
 Changes to be committed:
	modified:   contribute/contribute_documentation.rst
- Add Sphinx linkcheck documentation before submitting for installed and
  docker version
- some cosmetic formatting changes

### Checklist
- [X] With the proposed changes no Sphinx errors or warnings are generated.
- [X] I have added my name to the AUTHORS file, if required (descending alphabetical order).

2023-09-22 18:48 UTC, FroggyFlox requested changes
Thanks a lot for taking care of this so quickly!
I just noticed a typo, otherwise I'm personally all good with it.

2023-09-22 18:48 UTC, FroggyFlox commented on contribute/contribute_documentation.rst
> +tool that comes with Sphinx. During PR submission that link check is also runs automatically.
Minor typo:
```suggestion
tool that comes with Sphinx. During PR submission that link check is also run automatically.
```

2023-09-22 19:48 UTC, FroggyFlox approved these changes

2023-09-25 12:39 UTC, phillxnet commented
@Hooverdan96 Thanks again. Nice find and fix.
@FroggyFlox Thanks for the review: much appreciated.

Merging & publishing directly.

2023-09-25 12:39 UTC, merged

2023-09-25 12:41 UTC, phillxnet commented
PR product PRODUCTION published.