Document resetting Rock-on Root #434
rockstor/rockstor-doc pull request #503
Opened 2024-10-23 17:24 UTC by Hooverdan96

Fixes #434 .

### This pull request's proposal (superseeding PR #502).
add the Rock-on root reset process to the section that deals with uninstalling/installing Rock-ons. Also, some minor cleanups in the same file.

### Checklist
- [X] With the proposed changes no Sphinx errors or warnings are generated.
- [X] I have added my name to the AUTHORS file, if required (descending alphabetical order).

**Note:** Linkcheck will continue to fail until a currently open PR has been merged.

2024-10-25 12:45 UTC, phillxnet commented
@Hooverdan96 Re:

> **Note:** Linkcheck will continue to fail until a currently open PR has been merged.

This also requires that this branch be re-based. But not required as we know the failure now. And I have now merged that PR. So we are hopefully getting ahead of the little thorn.

About to review this now so no need to re-base by the way.

2024-10-25 13:45 UTC, phillxnet requested changes
@Hooverdan96 Thanks for yet-another great addition.

I'm a bit concerned about folks jumping to this brute-force solution: but there are warnings in there. But this is rather the nuclear option in my opinion. But as you indicated here, it can be necessary on occasions. So it can only be good to have it documented as you've presented. Thanks.

See what you think of my suggested changes, almost all trivial actually; but hopefully also nice-to-have.

My main indicator that this this procedure is necessary has been log entries to the effect that a subvol/snapshot was was missing pertaining to a docker container. What we likely need in rockstor-core here is more use of:
```
docker system prune -a --volumes
```
And maybe that could be added to this doc as a pre-nuclear (wipe / recreate) option. And only if that, once run, followed by a Pool refresh to update subvols fails to work do we then suggest this rather radical option of switching/refreshing the Rock-ons root share.

2024-10-25 13:45 UTC, phillxnet commented on interface/overview.rst
> +As a one-time setup activity, it is also necessary create
```suggestion
As a one-time setup activity, it is also necessary to create
```

2024-10-25 13:45 UTC, phillxnet commented on interface/overview.rst
> +conflict that may arise with a mixed-used share. The Rock-ons root share is
```suggestion
conflict that may arise with a mixed-use share. The Rock-ons root share is
```

@Hooverdan96 I know this was the case before, but just noting while I'm here.

2024-10-25 13:45 UTC, phillxnet commented on interface/overview.rst
>  from a mixed used share has the potential to break the installed Rock-ons.
```suggestion
from a mixed-use share has the potential to break the installed Rock-ons.
```

Again this does not pertain to your alterations but we could slip this in as we go.

2024-10-25 13:45 UTC, phillxnet commented on interface/overview.rst
> +Reset Rock-on Root
```suggestion
Reset The Rock-ons Root
```

@Hooverdan96 I prefer this reference as it is the root for all rock-ons, not for a single rock-on. And our pics and other doc references hopefully mostly conform to this arbitrary but important reference. [EDIT] ~~I know a 'the' could be nice but we are titles here so I think this floats :) .~~

2024-10-25 13:45 UTC, phillxnet commented on interface/overview.rst
> +   right back to where it was before the Rock-on root reset process.
```suggestion
   right back to where it was before the Rock-ons root reset process.
```

2024-10-25 13:45 UTC, phillxnet commented on interface/overview.rst
> +* Turn off Rock-ons Service (either on the Rockons page directly, or via the
```suggestion
* Turn off the Rock-ons Service (either on the Rockons page directly, or via the 
```

2024-10-25 13:45 UTC, phillxnet commented on interface/overview.rst
> +* Following :ref:`rockons_root`, either create a new Rock-on root share with
```suggestion
* Following :ref:`rockons_root`, to either create a new Rock-ons root share with
```

2024-10-25 13:45 UTC, phillxnet commented on interface/overview.rst
> +  a different name, or delete and recreate the Rock-on root share with its original name.
```suggestion
  a different name, or delete and recreate the Rock-ons root share with its original name.
```

2024-10-25 13:45 UTC, phillxnet commented on interface/overview.rst
> +  In case of creating a new Rock-on root share with a different name, adjust the Rock-ons
```suggestion
  In the case of creating a new Rock-ons root share with a different name, adjust the Rock-ons
```

2024-10-25 13:45 UTC, phillxnet commented on interface/overview.rst
> +  Service setting by selecting the new share name from the dropdown. If the Rock-on root
```suggestion
  Service setting by selecting the new share name from the dropdown. If the Rock-ons root
```

2024-10-25 13:45 UTC, phillxnet commented on interface/overview.rst
> +and only result in the re-installation of the previously capture Rock-ons.
```suggestion
and only result in the re-installation of the previously installed Rock-ons.
```

2024-10-25 14:57 UTC, Hooverdan96 commented
Thanks for the suggestions, I've accepted them. I will incorporate your additional comments from above and bring these back (and address the current Sphinx failure that now seems to have popped up).

2024-10-25 15:27 UTC, phillxnet commented
@Hooverdan96 Thanks. Let me know when I should re-test and publish:
Re the Sphinx error:

```
Reset The Rock-ons Root
------------------ [docutils]
/home/runner/work/rockstor-doc/rockstor-doc/interface/overview.rst:503: WARNING: Title underline too short.
```
Yes, that one was down to me I'm afraid. I failed to also modify the number of chars indicating a sub-header to match the sub-header changes I made. My apologies for the extra work there.

2024-10-25 17:09 UTC, Hooverdan96 commented
@phillxnet, I did end up rebasing the branch, and rearranged the nuclear option to be after a section on pruning, and also updated the logs symptom with your comment about missing subvols.

2024-10-25 21:23 UTC, Hooverdan96 commented
The linkcheck failures this time around where related to `smartmontools` links, which timed out (first time for me). i assume those are temporary at this point:
```
(    howtos/smart: line    6) timeout   https://www.smartmontools.org/ - HTTPSConnectionPool(host='www.smartmontools.org', port=443): Read timed out. (read timeout=20)
(    howtos/smart: line  191) timeout   https://www.smartmontools.org/browser/trunk/smartmontools/smartctl.8.in - HTTPSConnectionPool(host='www.smartmontools.org', port=443): Read timed out. (read timeout=20)
(    howtos/smart: line   94) timeout   https://www.smartmontools.org/browser/trunk/smartmontools/smartd.conf.5.in - HTTPSConnectionPool(host='www.smartmontools.org', port=443): Read timed out. (read timeout=20)
(    howtos/smart: line  193) timeout   https://www.smartmontools.org/wiki/Supported_RAID-Controllers - HTTPSConnectionPool(host='www.smartmontools.org', port=443): Read timed out. (read timeout=20)
```

2024-10-26 13:36 UTC, phillxnet approved these changes

2024-10-26 13:41 UTC, phillxnet commented
@Hooverdan96 Thanks for including that extra command, may end-up saving some folks from having to do the more extensive reset procedure.

I'll merge and get this published. As always much appreciated. It's great to have this procedure finally documented. In time we can automate better a Rock-on reset, or have Web-UI intergration for force uninstall and the like; but bit-by-bit.

2024-10-26 13:41 UTC, merged

2024-10-26 13:43 UTC, phillxnet commented
Re the smartmontools linkcheck hick-up, a couple of builds locally did not show this failure. So as you surmised I think we caught them on a bad day. Or they don't like GitHub actions accessing their site.

2024-10-26 13:45 UTC, phillxnet commented
PR product PRODUCTION published.