Adguard home instructions
rockstor/rockstor-doc pull request #517
Opened 2024-12-27 16:32 UTC by BrokenOnedroid

> To ease and accelerate the PR submission, please use the template below to provide all required information.
> Please see our "Contributing to Rockstor documentation" in our [Rockstor's documentation](http://rockstor.com/docs/contribute_documentation.html)

Fixes #
If this is okay to use. The description in the PR can be linked to this Page. And then added to the rockon-registry. (See: rockstor/rockon-registry#397)

### This pull request's proposal
Added write up for AdGuard Home Rock-on installation. 

### Checklist
- [x] With the proposed changes no Sphinx errors or warnings are generated.
- [ ] I have added my name to the AUTHORS file, if required (descending alphabetical order).

2024-12-28 14:05 UTC, phillxnet commented
@BrokenOnedroid Thanks for seeing to this doc entry to complement your on-going Rock-on contributions ; much appreciated.

I've just run the Sphinx test build via this repos GitHub Action and we look to have an issue via the following Warning:

https://github.com/rockstor/rockstor-doc/actions/runs/12518381636/job/34940209577?pr=517#step:5:97

> /home/runner/work/rockstor-doc/rockstor-doc/interface/docker-based-rock-ons/adguard-home.rst: WARNING: document isn't included in any toctree

Which suggests this pull requests branch is missing a toc (Table Of Content) entry for the page your have added. I.e. there is no menu entry generated for folks to find this new page.

- Take a looks at the other "Rock-ons with write-ups" toc section in: https://github.com/rockstor/rockstor-doc/blob/master/interface/overview.rst

Which in-turn ends-up being html rendered as:

- https://rockstor.com/docs/interface/overview.html#rock-ons-with-write-ups

Also note:
- you are authoring these commits under:  https://github.com/abandonedforce
- but the pull request is authored under: https://github.com/BrokenOnedroid

It would likely be better to use only one GitHub account here as it makes attribution easier. I suspect your local development environment is setup with the former: but you likely intend to use the later. We have a docs section with some details on configuring this:

- Local git repo setup: https://rockstor.com/docs/contribute/contribute.html#local-git-repo-setup

Also keep in mind the second tick item: i.e. we like folks to get attribution for their submissions. But your choice of course.

Hope that helps.

2024-12-28 14:07 UTC, phillxnet commented
@BrokenOnedroid My apologies if I've jumped in too early here on this Draft status PR.

2024-12-29 12:29 UTC, BrokenOnedroid commented
@phillxnet thanks for pointing these things out. 
I still need to check grammar and so on, its a wip.

I did not realize that my old username is used. I rename the github user sometime ago.
But i don't seem able to get the username in the commits changed. Any idea?

![git_settings](https://github.com/user-attachments/assets/5cb16a77-8a7b-4089-a1dd-42f37a89e297)

2024-12-29 16:37 UTC, phillxnet commented
> But i don't seem able to get the username in the commits changed. Any idea?

I think what is happening is that the username against old commits is not changed by altering the current config. But if you changed your local config and then did this latest commit then you likely also have to modify the associated email. GitHub I think uses the email to track commits.  Note the other command in our docs e.g.:

> git config user.email your_email_address

Plus upon this Pull Request reaching non-draft status, you can squashing all commits down to one under the new GitHub user and email. A submission will be required but that's not bother. I've taken to doing this myself quite a lot as it makes asking questions / opinions on draft work easier. And once all is ready one can then just squash and remove the remote (GitHub) branch and push again in the new squashed (single commit) status. That will then hopefully have the new user against the commit also.

Check your two GitHub accounts and compare the emails there-in. The PR is down OK as having been submitted by @BrokenOnedroid but the commits are all under that old account. So I'm guessing there is an email association that has precedence.

Feel free to experiment here in this PR as it will likely be squashed into a single commit and resubmitted later anyway given this is an example of a shared  in-development branch: with the appropriate Draft status so we can all appreciate the in-development nature: as you say WIP. Looking nice though.

Hope that helps.

2025-01-04 19:13 UTC, BrokenOnedroid commented
From my pov i added everything necessary into the instructions. 

`make html` does not produce errors.
`make linkcheck` shows errors, but these are `HTTPSConnectionPool` unrelated to my changes.

2025-01-15 17:21 UTC, Hooverdan96 requested changes
Content looks great! I suggested the Rock-on capitalization and a bit of semantic line-breaking that @phillxnet would like to move to (though I was probably not consistent in that). I am also suggesting the macvlan network creation using the WebUI System Shell.

2025-01-15 17:21 UTC, Hooverdan96 commented on interface/docker-based-rock-ons/adguard-home.rst
> +with a command that needs to be changed to match your local network.
```suggestion
Now we need to add the *macvlan-network* for the Rock-on.
Using the WebUI's System Shell, execute the command below, after adjusting it according to your local network settings. Since this requires an elevated command prompt, have the `root` user password ready:
```

2025-01-15 17:21 UTC, Hooverdan96 commented on interface/docker-based-rock-ons/adguard-home.rst
> +   docker network create -d macvlan --subnet=192.168.178.0/24 --ip-range=192.168.178.58/32 --gateway=192.168.178.1 -o parent=eth0 adguard-home
```suggestion
   sudo docker network create -d macvlan --subnet=192.168.178.0/24 --ip-range=192.168.178.58/32 --gateway=192.168.178.1 -o parent=eth0 adguard-home
```
Since not everyone is using a terminal program to access their Rockstor instance I suggest that the command is executed using the WebShell in the Rockstor UI. Since that doesn't allow for a direct root user login, it would require the `sudo` + root password.

2025-01-15 17:21 UTC, Hooverdan96 commented on interface/docker-based-rock-ons/adguard-home.rst
> +rock-on configuration.
```suggestion
The last entry of the *adguard-home* command must be kept the same.
This network name is set in the Rock-on configuration.
```

2025-01-15 17:21 UTC, Hooverdan96 commented on interface/docker-based-rock-ons/adguard-home.rst
> +page.
```suggestion
We are now ready to start the installation of the AdGuard Home Rock-on.
Click on the *Install* button next to the **AdGuard Home** listing on the *Rock-ons* page.
```

2025-01-15 17:21 UTC, Hooverdan96 commented on interface/docker-based-rock-ons/adguard-home.rst
> +Use the shares we set up earlier.
```suggestion
We just need to assign the shares for the installation.
Set them in the web interface, using the shares that were set up earlier.
```

2025-01-15 17:21 UTC, Hooverdan96 commented on interface/docker-based-rock-ons/adguard-home.rst
> +These ports are set without any user interaction.
```suggestion
This is the port used to access the AdGuard Home web interface.
Note that port *3000* is the port for the initial configuration.
After configuration, the Web UI will be accessible on port *80* or *443*.
These ports are set without any user interaction.
```

2025-01-15 17:21 UTC, Hooverdan96 commented on interface/docker-based-rock-ons/adguard-home.rst
> +You'll see a screen indicating that the Rock-on is being installed.  Click Close.
```suggestion
You'll see a screen indicating that the Rock-on is being installed.
Click Close.
```

2025-01-15 17:21 UTC, Hooverdan96 commented on interface/docker-based-rock-ons/adguard-home.rst
> +
```suggestion
In this example, the *--ip-range* value is the single IP address: *192.168.178.58*. 
Please select an unused IP address in your local *--ip-range*.
If you use a DHCP server either reserve this address permanently 
or choose an address outside the DHCP server range.

The value for *-gateway* must be set to the IP address of the gateway of your local network.

The value for *-parent* must be set to the name of your network. This can be found under *System* > *Network*.
The default and expected value is *eth0*. 

```

2025-01-15 17:21 UTC, Hooverdan96 commented on interface/docker-based-rock-ons/adguard-home.rst
> +Before you install the Adguard Home rock-on, you should understand the
```suggestion
Before you install the Adguard Home Rock-on, you should understand the
```

2025-01-15 17:21 UTC, Hooverdan96 commented on interface/docker-based-rock-ons/adguard-home.rst
> +Note that there is some preparation required to get this rock-on to work.
```suggestion
Note that there is some preparation required to get this Rock-on to work.
```

2025-01-15 17:21 UTC, Hooverdan96 commented on interface/docker-based-rock-ons/adguard-home.rst
> +This rock-on requires two additional shares to be set.
```suggestion
This Rock-on requires two additional shares to be set. 
```

2025-01-18 17:22 UTC, BrokenOnedroid commented
@Hooverdan96 all suggested changes are reasonable. So I committed all of them.

2025-01-19 19:39 UTC, Hooverdan96 commented
@phillxnet, from my perspective this looks good. If you don't have any other concerns, I think this could be ready for a merge.

2025-01-24 16:57 UTC, phillxnet commented
@BrokenOnedroid Thanks for this super helpful Rock-on howto.

I'll merged & published, as per @Hooverdan96 recommendations, and to untangle our chicken & egg situation re your now ready for review PR of the associated Rock-on itself :).

- https://github.com/rockstor/rockon-registry/pull/397

We can always re-visit this doc entry for the trivial elements I've noted below.
No worries regarding this doc entry being published ahead of the associated Rock-on PR merge. I see it as the better way around anyway as reviewers of the Rock-on PR have the doc entry to follow during the review process.

## Redundancy re link text:

![Redundancy-re-link](https://github.com/user-attachments/assets/b45e0205-a580-46f1-bb9c-eaabbff4ab3d)

In above we have repeat text once rendered.

![Redundancy-re-link2](https://github.com/user-attachments/assets/0233ed08-c6a6-4867-b4eb-fa0671021144)

And here we can re-word to have the `document` word be our link, rather than the redundancy of "can be found here: ...". I.e. I think it's nicer to just have a link to the upstream docs, it may not even need it's own sub-section. But the note there re required config is really the key part. Any maybe we should lead with that and rename that subsection. But no worries as this can all be re-visited and the key element here is the requirement for this doc generally to enable the work you've done on the Rock-on.

## Repeat word.

> Navigate to to Access Control and click on Edit. "

@Hooverdan96 We should probably, in-time, try for some kind of automated check on PR's for spelling and repeat word errors such as this (and my own frequent typos of this sort). There will likely be additional plugins for Sphinx itself for this kind of thing.

Didn't want to hold up publishing just for these trivial typos/rewords given the inter-dependencies re the Rock-on itself.

---

I think it's also good to include, along with these by-hand configurations (a product of our fledgling Rock-ons subsystem) their equivalent undo procedures. I.e. in the case of this doc entry, a note on how to remove the added vlan for example.

2025-01-24 17:00 UTC, merged

2025-01-24 17:05 UTC, phillxnet commented
PRODUCTION published